# configuration for log4rs crate
refresh_rate: 10 seconds # interval for checking config changes
appenders:
  stdout:
    kind: console
root:
#  level: debug
  level: error
  appenders:
    - stdout
loggers:
#  mio:
#    level: warn
  mio_extras: 
    level: warn
#  rustdds::dds::qos:
#    level: trace
#  rustdds::network::udp_listener:
#    level: trace
#  rustdds::discovery::discovery:
#    level: warn